name: PR Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      # Para HTML puro não precisa de build extra.
      # Se futuramente usar React/Vue/etc, adicione aqui.

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          cname: false   # Impede que o preview use seu domínio customizado

